# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('HDI.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[4.29000e-01 1.78700e+03 5.79000e+01]
 [4.33000e-01 1.76600e+03 5.84000e+01]
 [4.40000e-01 1.82500e+03 5.89000e+01]
 [4.46000e-01 1.87700e+03 5.93000e+01]
 [4.53000e-01 1.96600e+03 5.98000e+01]
 [4.61000e-01 2.07800e+03 6.03000e+01]
 [4.68000e-01 2.19700e+03 6.08000e+01]
 [4.74000e-01 2.24500e+03 6.12000e+01]
 [4.81000e-01 2.34100e+03 6.17000e+01]
 [4.89000e-01 2.50400e+03 6.21000e+01]
 [4.95000e-01 2.54800e+03 6.25000e+01]
 [4.99000e-01 2.63000e+03 6.29000e+01]
 [5.06000e-01 2.68900e+03 6.33000e+01]
 [5.18000e-01 2.85100e+03 6.37000e+01]
 [5.27000e-01 3.02900e+03 6.41000e+01]
 [5.36000e-01 3.21700e+03 6.45000e+01]
 [5.46000e-01 3.42100e+03 6.49000e+01]
 [5.55000e-01 3.64000e+03 6.53000e+01]
 [5.63000e-01 3.69100e+03 6.58000e+01]
 [5.69000e-01 3.92600e+03 6.62000e+01]
 [5.79000e-01 4.18200e+03 6.67000e+01]
 [5.88000e-01 4.35300e+03 6.71000e+01]
 [5.97000e-01 4.52100e+03 6.75000e+01]
 [6.04000e-01 4.74900e+03 6.79000e+01]
 [6.16000e-01 5.04700e+03 6.83000e+01]
 [6.24000e-01 5.39100e+03

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [5]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [6]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[13.07 11.9 ]
 [15.8  16.  ]
 [15.84 16.  ]
 [ 8.53  8.3 ]
 [15.78 15.9 ]
 [11.04 11.5 ]
 [ 8.38  8.2 ]
 [ 8.83  8.3 ]
 [11.72 11.4 ]
 [16.72 17.5 ]
 [10.26 10.5 ]
 [13.75 12.2 ]
 [ 7.66  7.9 ]
 [13.99 13.7 ]
 [15.81 16.3 ]
 [16.02 16.5 ]
 [ 9.28 10.3 ]
 [11.21 11.1 ]
 [16.02 16.3 ]
 [16.03 16.1 ]
 [14.9  14.5 ]
 [14.79 14.3 ]
 [ 9.95  9.9 ]
 [11.45 11.9 ]]


In [8]:
from sklearn.metrics import mean_squared_error, r2_score
# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(y_test, y_pred))

Mean squared error: 0.32
Coefficient of determination: 0.97
